#!/bin/bash

port="4000"

ask() {
    while true; do
        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi
        read -p "$1 [$prompt] " REPLY </dev/tty
        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi
        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}


case ${@:1:1} in
    setup)
    # Setup .env file
    if [ ! -f ".env" ]; then
      echo "Creating .env file."
      cp .env.example .env
    fi
        # node
    if [ -f "package.json" ]; then
        if [ -f "node_modules" ]; then
            echo -e "\t Installing npm dependencies..."
            npm install
        else
            if ask "Would you like to update your npm dependencies?"; then
                echo -e "\t Updating npm dependencies..."
                npm update
            fi
        fi
    fi
    # bower
    if [ -f "bower.json" ]; then
        if [ -f "node_modules" ]; then
            echo -e "\t Installing bower dependencies..."
            bower install
        else
            if ask "Would you like to update your bower dependencies?"; then
                echo -e "\t Updating bower dependencies..."
                bower update
            fi
        fi
    fi
    echo ''

    # composer
    if [ -f "composer.json" ]; then
        if [ -f "composer.lock" ]; then
            if ask "Would you like to update your composer dependencies?"; then
                echo -e "\t Updating composer dependencies..."
                composer update
            fi
        else
            echo -e "\t Installing composer dependencies..."
            composer install
        fi
    fi
    echo ''
    fi
    ;;
    watch)
    ;;
    go)
      # Start PHP server
      pushd public
      php -S localhost:${port}
    ;;
    dev)
    gulp dev

    ;;
    deploy)
    php artisan migrate
    gulp stage
    git fetch --all
    git reset --hard origin/master
    git pull origin master




    ;;
    **)
        echo ''
        echo -e "setup"
        echo -e "\t" "Sets up your local environment for development."

        echo ''
        echo -e "go"
        echo -e "\t" "Run the project at localhost:${port}."

        echo ''
        echo -e "watch"
        echo -e "\t" "Run the default preprocessor watch task (gulp, grunt, etc.)."

    ;;
esac
